/**
 * Bookmarks.js
 *
 * @description :: TODO: You might write a short summary of how this model works and what it represents here.
 * @docs        :: http://sailsjs.org/documentation/concepts/models-and-orm/models
 */

module.exports = {

  tableName: 'bookmarks',


  attributes: {
    // e.g. unique identifier for the bookmark generated by database
    id: {
      type: 'string',
      unique: true,
      primaryKey: true
    },

    url: {
      type: 'string'
    },
    tags: {
      type: 'array'
    }

  }
};

